// House edge for a rule set: exact engine values from data/edges.json (generated by tools/gen-edges.js),
// with the blackjack-payout cost applied analytically (it never changes strategy).
import { normalizeRules } from '../engine/rules.js';

let table = null;
export async function loadEdges() {
  if (table) return table;
  try { table = await (await fetch('data/edges.json')).json(); } catch { table = { edges: {} }; }
  return table;
}

// P(player natural AND dealer has no natural) for a fresh shoe of `decks` decks.
export function pPlayerBJ(decks) {
  const d = Number.isFinite(decks) ? decks : 1e6;
  const N = 52 * d, A = 4 * d, T = 16 * d;
  let q = 0;
  for (const [p1, p2] of [['A', 'T'], ['T', 'A']]) {
    const c = { A, T, o: N - A - T };
    const a = c[p1] / N; c[p1]--; let n = N - 1;
    for (const up of ['A', 'T', 'o']) {
      const pu = c[up] / n; c[up]--; n--;
      const b = c[p2] / n; c[p2]--; n--;
      const pbj = up === 'A' ? c.T / n : up === 'T' ? c.A / n : 0;
      q += a * pu * b * (1 - pbj);
      c[p2]++; c[up]++; n += 2;
    }
  }
  return q;
}
// Cost in percentage points of paying `pays` instead of 3:2.
export const bjCost = (decks, pays) => (1.5 - pays) * pPlayerBJ(decks) * 100;

const PEEK_CODE = { both: 'B', ace: 'A', none: 'N' };
export const gridKey = (r) => [r.decks, +r.dealerHitsSoft17, +r.doubleAfterSplit, +r.resplitAces, r.surrender === 'late' ? 1 : 0, PEEK_CODE[r.peekOn], r.doubleRestriction === 'any' ? 'A' : 'N'].join('|');

// Returns house edge in percent (positive = house), or null if the rule set is outside the grid.
export async function houseEdge(rulesIn) {
  const r = normalizeRules(rulesIn);
  const t = await loadEdges();
  const base = t.edges[gridKey(r)];
  if (base === undefined) return null;
  return base + bjCost(r.decks, r.blackjackPays);
}
