// Generates data/edges.json: exact house edge (engine output) for every rule combination the
// Rules Panel Reader can show. Blackjack payout is NOT in the grid: it never changes strategy, so
// the 6:5 cost is applied analytically (see engine/edges.js). Run: node tools/gen-edges.js
import { Worker, isMainThread, parentPort, workerData } from 'node:worker_threads';
import { writeFileSync, mkdirSync } from 'node:fs';
import os from 'node:os';
import { Solver } from '../engine/ev.js';
import { DEFAULT_RULES } from '../engine/rules.js';

const DECKS = [1, 2, 4, 6, 8];
const PEEK_CODE = { both: 'B', ace: 'A', none: 'N' };
function configs() {
  const out = [];
  for (const decks of DECKS) for (const h17 of [false, true]) for (const das of [true, false])
    for (const rsa of [false, true]) for (const dbl of ['any', '9-11'])
      for (const mode of ['peek', 'peek+LS', 'peek-ace', 'enhc'])
        out.push({ decks, dealerHitsSoft17: h17, doubleAfterSplit: das, resplitAces: rsa, doubleRestriction: dbl,
          peekOn: mode === 'enhc' ? 'none' : mode === 'peek-ace' ? 'ace' : 'both',
          surrender: mode === 'peek+LS' ? 'late' : 'none', blackjackPays: 1.5 });
  return out;
}
export const keyOf = (c) => [c.decks, +c.dealerHitsSoft17, +c.doubleAfterSplit, +c.resplitAces, c.surrender === 'late' ? 1 : 0, PEEK_CODE[c.peekOn], c.doubleRestriction === 'any' ? 'A' : 'N'].join('|');

if (isMainThread) {
  const all = configs();
  const n = Math.max(1, os.cpus().length - 1);
  const buckets = Array.from({ length: n }, () => []);
  // interleave so heavy (8D) configs spread evenly
  all.forEach((c, i) => buckets[i % n].push(c));
  const edges = {};
  let done = 0;
  const t0 = Date.now();
  for (const b of buckets) {
    const w = new Worker(new URL(import.meta.url), { workerData: b });
    w.on('message', (m) => {
      edges[m.key] = +m.edge.toFixed(6);
      if (++done % 10 === 0) console.log(`${done}/${all.length}  ${((Date.now() - t0) / 1000).toFixed(0)}s`);
      if (done === all.length) {
        mkdirSync(new URL('../data/', import.meta.url), { recursive: true });
        writeFileSync(new URL('../data/edges.json', import.meta.url), JSON.stringify({
          note: 'House edge in percent (positive = house), exact composition-dependent play, resplit to 4 hands, blackjack 3:2. Generated by tools/gen-edges.js from engine/ev.js.',
          key: 'decks|H17|DAS|RSA|LS|peekOn(B=both,A=ace-only,N=none)|dbl(A=any,N=9-11 only)', generated: new Date().toISOString().slice(0, 10), edges,
        }));
        console.log('wrote data/edges.json', Object.keys(edges).length, 'entries in', ((Date.now() - t0) / 1000).toFixed(0), 's');
        process.exit(0);
      }
    });
  }
} else {
  for (const c of workerData) {
    const e = new Solver({ ...DEFAULT_RULES, ...c }).houseEdge().edge * 100;
    parentPort.postMessage({ key: keyOf(c), edge: e });
  }
}
